project:
  type: website

website:
  title: "aidememoire"
  site-url: https://aidememoire.netlify.app
  sidebar:
    contents:
      - rstats.qmd
      - sql.qmd
    style: "docked"  
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/simoncoulombe/aidememoire

lang: fr    # default post language is french
lightbox: auto    # allows clicking on images to enlarge them
language: 
  title-block-author-single: "Auteur" #  i know my gender..https://github.com/quarto-dev/quarto-cli/discussions/2796#discussioncomment-3851669
format:
  html:
    theme: simplex
    css: styles.css
    code-overflow: wrap
    code-fold: true
    code-folding: show
    code-summary: "\\<code\\>" 
    code-copy: hover # the copy code icon appears when hovering above code chunk
    email-obfuscation: javascript
editor: source
execute:
  freeze: auto

